/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.zabalburu.zabalevent.views;

import java.awt.Image;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.zabalburu.zabalevent.modelo.Categoria;
import net.zabalburu.zabalevent.modelo.Evento;
import net.zabalburu.zabalevent.modelo.Lugar;
import net.zabalburu.zabalevent.modelo.Usuario;
import net.zabalburu.zabalevent.service.ZabalEventService;

/**
 *
 * @author Iñigo
 */
public class NuevoEventoForm extends javax.swing.JFrame {

    private Usuario usuario;
    private static ZabalEventService service = new ZabalEventService();
    private File f;
    /**
     * Creates new form NuevoEventoForm
     */
    public NuevoEventoForm(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        cargarCombos();
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlBotones = new javax.swing.JPanel();
        btnAñadirEvento = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        pnlTitulo = new javax.swing.JPanel();
        lblTituloForm = new javax.swing.JLabel();
        pnlDatos = new javax.swing.JPanel();
        lblTituloId = new javax.swing.JLabel();
        lblIdEvento = new javax.swing.JLabel();
        lblFotoUsuario = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        jspDescripcion = new javax.swing.JScrollPane();
        txaDescripcion = new javax.swing.JTextArea();
        lblCategoria = new javax.swing.JLabel();
        cbxCategoria = new javax.swing.JComboBox<>();
        lblLugar = new javax.swing.JLabel();
        cbxLugar = new javax.swing.JComboBox<>();
        lblFotoLugar = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        ftxFecha = new javax.swing.JFormattedTextField();
        lblPrecio = new javax.swing.JLabel();
        ftxPrecio = new javax.swing.JFormattedTextField();
        lblFotoEvento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Evento");

        pnlBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnAñadirEvento.setText("Añadir Evento");
        btnAñadirEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirEventoActionPerformed(evt);
            }
        });
        pnlBotones.add(btnAñadirEvento);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        pnlBotones.add(btnVolver);

        getContentPane().add(pnlBotones, java.awt.BorderLayout.PAGE_END);

        pnlTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTituloForm.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTituloForm.setText("Nuevo Evento");
        pnlTitulo.add(lblTituloForm);

        getContentPane().add(pnlTitulo, java.awt.BorderLayout.PAGE_START);

        pnlDatos.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        pnlDatos.setLayout(new java.awt.GridBagLayout());

        lblTituloId.setText("Id. Evento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlDatos.add(lblTituloId, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlDatos.add(lblIdEvento, gridBagConstraints);

        lblFotoUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlDatos.add(lblFotoUsuario, gridBagConstraints);

        lblTitulo.setText("Título");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlDatos.add(lblTitulo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlDatos.add(txtTitulo, gridBagConstraints);

        lblDescripcion.setText("Descripción");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlDatos.add(lblDescripcion, gridBagConstraints);

        txaDescripcion.setColumns(20);
        txaDescripcion.setRows(5);
        jspDescripcion.setViewportView(txaDescripcion);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlDatos.add(jspDescripcion, gridBagConstraints);

        lblCategoria.setText("Categoría");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlDatos.add(lblCategoria, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlDatos.add(cbxCategoria, gridBagConstraints);

        lblLugar.setText("Lugar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlDatos.add(lblLugar, gridBagConstraints);

        cbxLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLugarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlDatos.add(cbxLugar, gridBagConstraints);

        lblFotoLugar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlDatos.add(lblFotoLugar, gridBagConstraints);

        lblFecha.setText("Fecha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlDatos.add(lblFecha, gridBagConstraints);

        ftxFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlDatos.add(ftxFecha, gridBagConstraints);

        lblPrecio.setText("Precio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlDatos.add(lblPrecio, gridBagConstraints);

        ftxPrecio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlDatos.add(ftxPrecio, gridBagConstraints);

        lblFotoEvento.setToolTipText("Click para añadir una imagen");
        lblFotoEvento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFotoEvento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFotoEvento.setMaximumSize(new java.awt.Dimension(120, 120));
        lblFotoEvento.setMinimumSize(new java.awt.Dimension(120, 120));
        lblFotoEvento.setPreferredSize(new java.awt.Dimension(120, 120));
        lblFotoEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblFotoEventoMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlDatos.add(lblFotoEvento, gridBagConstraints);

        getContentPane().add(pnlDatos, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(597, 592));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbxLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLugarActionPerformed
        Lugar l = (Lugar) cbxLugar.getSelectedItem();
        ImageIcon imIc = new ImageIcon("imagenes/lugares/"
                + l.getFoto());
        Image imag = imIc.getImage();
        /*imag = imag.getScaledInstance(

                imIc.getIconWidth()/4, 
                imIc.getIconHeight()/4, Image.SCALE_SMOOTH);
        imag = imag.getScaledInstance(
                120, 
                120, Image.SCALE_SMOOTH);*/
        int max = Math.max(imIc.getIconWidth(), imIc.getIconHeight());
        double fe = 120.0 / max;
        imag = imag.getScaledInstance(
                (int) (imIc.getIconWidth() * fe),
                (int) (imIc.getIconHeight() * fe), Image.SCALE_SMOOTH);
        imIc.setImage(imag);
        lblFotoLugar.setIcon(imIc);
    }//GEN-LAST:event_cbxLugarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        new MainForm(usuario);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAñadirEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirEventoActionPerformed
        if (txtTitulo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe especificarse el título del evento",
                    "Falta Título Evento",
                    JOptionPane.ERROR_MESSAGE);
            txtTitulo.requestFocus();
        } else {
            Evento e = new Evento();
            e.setIdEvento(Integer.parseInt(lblIdEvento.getText()));
            e.setTitulo(txtTitulo.getText());
            e.setDescripcion(txaDescripcion.getText());
            Categoria c = (Categoria) cbxCategoria.getSelectedItem();
            e.setIdCategoria(c.getIdCategoria());
            Lugar l = (Lugar) cbxLugar.getSelectedItem();
            e.setIdLugar(l.getIdLugar());
            e.setIdUsuario(this.usuario.getIdUsuario());
            Date fecha = (Date) ftxFecha.getValue();
            e.setFecha(fecha);
            Number n = (Number) ftxPrecio.getValue();
            e.setPrecio(n.doubleValue());
            e.setFoto(f.getName());
            service.nuevoEvento(e);
            JOptionPane.showMessageDialog(this, "Evento guardado correctamente");
            this.mostrar();
        }
    }//GEN-LAST:event_btnAñadirEventoActionPerformed

    private void lblFotoEventoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFotoEventoMousePressed
        JFileChooser jfc = new JFileChooser();
        jfc.setMultiSelectionEnabled(false);
        jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileFilter filter = new FileNameExtensionFilter("JPEG (*.jpeg,*.jpg)", "jpg", "jpeg");
        jfc.addChoosableFileFilter(filter);
        filter = new FileNameExtensionFilter("PNG (*.png)", "png");
        jfc.addChoosableFileFilter(filter);
        filter = new FileNameExtensionFilter("GIF (*.gif)", "gif");
        jfc.addChoosableFileFilter(filter);
        filter = new FileNameExtensionFilter("Todas las imágenes", "gif","png","jpg","jpeg","bmp");
        jfc.addChoosableFileFilter(filter);
        jfc.setAcceptAllFileFilterUsed(false);
        if (jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            f = jfc.getSelectedFile();
            File fd = new File("imagenes/eventos", f.getName());
            try {
                BufferedInputStream bis = new BufferedInputStream(
                        new FileInputStream(f));
                BufferedOutputStream bos = new BufferedOutputStream(
                        new FileOutputStream(fd));
                int c;
                while ((c = bis.read()) != -1) {
                    bos.write(c);
                }
                bos.flush();
                bos.close();
                bis.close();
                ImageIcon imIc = new ImageIcon("imagenes/eventos/" + f.getName());
                Image imag = imIc.getImage();
                /*imag = imag.getScaledInstance(

                imIc.getIconWidth()/4, 
                imIc.getIconHeight()/4, Image.SCALE_SMOOTH);
                imag = imag.getScaledInstance(
                120, 
                120, Image.SCALE_SMOOTH);*/
                int max = Math.max(imIc.getIconWidth(), imIc.getIconHeight());
                double fe = 120.0 / max;
                imag = imag.getScaledInstance(
                        (int) (imIc.getIconWidth() * fe),
                        (int) (imIc.getIconHeight() * fe), Image.SCALE_SMOOTH);
                imIc.setImage(imag);
                lblFotoEvento.setIcon(imIc);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(NuevoEventoForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(NuevoEventoForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_lblFotoEventoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoEventoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoEventoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoEventoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoEventoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoEventoForm(service.getUsuarios().get(0)).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadirEvento;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<Categoria> cbxCategoria;
    private javax.swing.JComboBox<Lugar> cbxLugar;
    private javax.swing.JFormattedTextField ftxFecha;
    private javax.swing.JFormattedTextField ftxPrecio;
    private javax.swing.JScrollPane jspDescripcion;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFotoEvento;
    private javax.swing.JLabel lblFotoLugar;
    private javax.swing.JLabel lblFotoUsuario;
    private javax.swing.JLabel lblIdEvento;
    private javax.swing.JLabel lblLugar;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloForm;
    private javax.swing.JLabel lblTituloId;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextArea txaDescripcion;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

    private void mostrar() {
        ImageIcon imIc = new ImageIcon("imagenes/"
                + this.usuario.getFoto());
        Image imag = imIc.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        imIc.setImage(imag);
        lblFotoUsuario.setIcon(imIc);
        List<Evento> eventos = service.getEventos();
        int idEvento;
        if (eventos.isEmpty()) {
            idEvento = 1;
        } else {
            idEvento = eventos.get(eventos.size() - 1).getIdEvento() + 1;
        }
        lblIdEvento.setText(String.valueOf(idEvento));
        txtTitulo.setText("");
        txaDescripcion.setText("");
        cbxCategoria.setSelectedIndex(0);
        cbxLugar.setSelectedIndex(0);
        ftxFecha.setValue(new Date());
        ftxPrecio.setValue(0.0);

    }

    private void cargarCombos() {
        for (Categoria c : service.getCategorias()) {
            cbxCategoria.addItem(c);
        }
        for (Lugar l : service.getLugares()) {
            cbxLugar.addItem(l);
        }
    }
}
